.386
.MODEL flat, stdcall
OPTION casemap:none
;INCLUDES
INCLUDE \masm32\include\windows.inc
INCLUDE \masm32\include\kernel32.inc
INCLUDE \masm32\include\masm32.inc
INCLUDE \masm32\include\masm32rt.inc
.DATA
	;VARIABLES PARA CREAR LA MATRIZ
	MATRIZ DW 676 DUP (0),0
	CadenaL DB "ABCDEFGHIJKLMNOPQRSTUVWXYZ",0
	salto DB 10d, 0
	ContadorL0 DB 0,0
	ContadorL1 DB 0,0
	ContadorL2 DB 26,0
	pos DB 0,0
	pos1 DB 0,0
	vAux DB 0,0
.CODE
main:
	;LLENAR LA MATRIZ CON CARACTERES
	CALL LLENARMATRIZ
	INVOKE ExitProcess, 0

LLENARMATRIZ PROC FAR
	XOR BX, BX
	XOR CX, CX
	XOR AX, AX
	XOR DX, DX
	LEA ESI, MATRIZ
	MOV AL, ContadorL2
	MOV ContadorL0, AL
CICLOL:
	MOV AL, ContadorL0
	CMP AL, 00h
	JE FINCICLOL
	;ENCONTRAR LA LETRA EN LA QUE DEBE DE EMPEZAR LA LETRA DE LA SIGUIENTE FILA
	CALL ENCONTRARLETRA
	MOV DL, [EDI]
	;INGRESAR A LA CADENA MATRIZ
	CALL INGRESARAMATRIZ
	INC pos
	DEC ContadorL0
JMP CICLOL
FINCICLOL:
	INVOKE StdOut, ADDR MATRIZ
RET
LLENARMATRIZ ENDP

ENCONTRARLETRA PROC NEAR
	MOV DL, pos
	MOV pos1, DL
	LEA EDI, CadenaL
ENCONTRAR:
	CMP pos1, 00h
	JE FINENCONTRAR
	DEC pos1
	INC EDI
JMP ENCONTRAR
FINENCONTRAR:
RET
ENCONTRARLETRA ENDP

INGRESARAMATRIZ PROC NEAR
	MOV AL, ContadorL2
	MOV ContadorL1, AL
INGRESO:
	CMP ContadorL1, 00h
	JE FININGRESO
	MOV DL, [EDI]
	CMP DL, 00h
	JNE SALTOINGRESO
	LEA EDI, CadenaL
SALTOINGRESO:
	MOV DL, [EDI]
	MOV [ESI], DL
	INC ESI
	INC EDI
	DEC ContadorL1
JMP INGRESO
FININGRESO:
RET
INGRESARAMATRIZ ENDP
END main